CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS users(
	uuid UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
	name VARCHAR(60) NOT NULL,
	email VARCHAR(60) UNIQUE NOT NULL,
	password VARCHAR(300) NOT NULL,
	is_adm BOOLEAN NOT NULL,
	updated_on TIMESTAMP NOT NULL,
  	created_on TIMESTAMP NOT NULL
);